api:
- api/**/*.go

client:
- client/**/*.go
- manager/client/**/*.go

documentation:
- README.md
- docs/*.md

golang:
- '**/*.go'

job:
- api/job/**/*.go

manager:
- manager/**/*.go

proto:
- manager/**/*.proto

scheduler:
- scheduler/**/*.go
- manager/scheduler/**/*.go

task:
- api/task/**/*.go

worker:
- worker/**/*.go
- manager/worker/**/*.go
